cssite/collect/urls.py
from django.urls import path
from . import views


app_name = "collect"
urlpatterns = [
    path('', views.index, name='index'),

    path('signup/', views.signup, name='signup'),

    path('login/', views.login, name='login'),

    path('userinfo/<int:pk>/', views.userinfo, name='userinfo'),
    path('logout/', views.logout, name='logout'),


    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('tasks/', views.TaskList.as_view(), name='tasks'),
    path('grader/', views.grader, name='grader'),
    path('submitter/', views.submitter, name='submitter'),

    path('manager/', views.manager, name='manager'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task-detail'),
    path('participations/', views.ParticipationList.as_view(), name='participations'),
    path('tasks/<int:pk>/create/', views.create_participation,
         name='create-participation'),
    path('participations/<int:pk>/delete/',
         views.delete_participation, name='delete-participation'),
    path('tasks/<int:pk>/parsedfiles/',
         views.parsedFileListAndUpload, name='submitted-parsedfiles'),
    path('graded-parsedfiles/', views.GradedfileList.as_view(),
         name='graded-parsedfiles'),
    path('allocated-parsedfiles/', views.AllocatedfileList.as_view(),
         name='allocated-parsedfiles'),
    path('allocated-parsedfiles/<int:pk>/',
         views.grade_parsedfile, name='grade-parsedfile'),
    path('allocated-parsedfiles/<int:pk>/download/',
         views.download_parsedfile, name='download-for-grade-parsedfile'),
    path('users/', views.UserList.as_view(), name='users'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
    #path('list/', fileuploadViews.fileList, name='list files'),

]

cssite/cssite/urls.py
from django.contrib import admin
from django.urls import path, include
from collect.views import *

# insecure media applying
from django.views.static import serve
from django.urls import re_path

urlpatterns = [
    path('', index, name='index'),

    path('admin/', admin.site.urls),
    path('collect/', include('collect.urls')),

    path('task/', listTasks, name='list tasks'),
    path('task/<int:task_id>/', showTask, name='show task'),
    path('task/<int:task_id>/download', downloadAllFiles, name='download all data'),
    path('task/<int:task_id>/end', endTask, name='end task'),

    path('task/part/<int:part_id>/ack', manager_acknowledge_participation, name='acknowledge participation'),
    path('task/part/<int:part_id>/del', manager_delete_participation, name='delete participation'),
    path('task/create/', createTask, name='create task'),
    path('task/<int:task_id>/parsedfiles/', parsedfile_list, name='parsedfile list'),
    path('task/<int:task_id>/parsedfiles/<int:user_id>/',
         submittedfile_list, name='submitted-parsedfiles'),

    path('task/<int:task_id>/parsedfile/<int:file_id>/grader/', grader_list, name='grader list'),
    path('task/<int:task_id>/parsedfile/<int:file_id>/grader/<int:account_id>/', allocate_file, name='allocate file'),

    path('task/<int:task_id>/attribute/',
         listAttributes, name='list attributes'),
    path('task/<int:task_id>/attribute/create/',
         createAttribute, name='create attribute'),

    path('task/<int:task_id>/derived_schema/',
         listDerivedSchemas, name='list derived schemas'),
    path('task/<int:task_id>/derived_schema/<int:schema_id>/',
         showDerivedSchema, name='show derived schema'),
    path('task/<int:task_id>/derived_schema/create/',
         createDerivedSchema, name='create derived schema'),
         
    path('task/<int:task_id>/derived_schema/<int:schema_id>/pair/',
         listMappingPairs, name='list mapping pairs'),
    path('task/<int:task_id>/derived_schema/<int:schema_id>/pair/create',
         createMappingPair, name='create mapping pair'),
     
    # insecure media applying
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

cssite/collect/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Account, Task, Participation, MappingInfo, SchemaAttribute, MappingPair, ParsedFile


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class GradeForm(forms.ModelForm):
    pass_state = forms.BooleanField(required=False)

    class Meta:
        model = ParsedFile
        fields = ['grading_score', 'pass_state']


# class SchemaChoiceForm(forms.ModelForm):
#     """
#     docstring
#     """
#     task = Task
#     mappingInfo = MappingInfo


# class UploadForm(forms.ModelForm):
#     """
#     docstring
#     """
#     class Meta:
#         model = ParsedFile
#         # fields = {'name', 'data'}
#         fields = ['derived_schema', 'file_original', 'start_date', 'end_date']

#     def save(self, commit=True):
#         self.instance = ParsedFile(**self.cleaned_data)

#         # if commit:
#         #     self.instance.save()
#             # self.instance.name = self.instance.file_original.name
#             # self.instance.save()
#         return self.instance


class CreateTask(forms.ModelForm):
    """
    docstring
    """
    class Meta:
        model = Task
        # fields = {'name', 'data'}
        fields = [
            'name',
            'minimal_upload_frequency',
            'description',
            'original_data_description',
        ]

    def save(self, commit=True):
        self.instance = Task(**self.cleaned_data)
        self.instance.activation_state = True

        if commit:
            self.instance.save()
            # self.instance.name = self.instance.file_original.name
            # self.instance.save()
        return self.instance


# class CreateSchemaAttribute(forms.ModelForm):
#     """
#     docstring
#     """
#     class Meta:
#         model = SchemaAttribute
#         fields = [
#             'attr',
#         ]

#     def save(self, task, commit=True):
#         self.instance = SchemaAttribute(**self.cleaned_data)
#         self.instance.task = task

#         if commit:
#             self.instance.save()
#             # self.instance.name = self.instance.file_original.name
#             # self.instance.save()
#         return self.instance


# class CreateMappingInfo(forms.ModelForm):
#     """
#     docstring
#     """
#     class Meta:
#         model = MappingInfo
#         # fields = {'name', 'data'}
#         fields = [
#             'derived_schema_name',
#         ]

#     def save(self, task, commit=True):
#         self.instance = MappingInfo(**self.cleaned_data)
#         self.instance.task = task

#         if commit:
#             self.instance.save()
#             # self.instance.name = self.instance.file_original.name
#             # self.instance.save()
#         return self.instance


# class CreateMappingPair(forms.ModelForm):
#     """
#     docstring
#     """
#     class Meta:
#         model = MappingPair
#         fields = [
#             # 'mapping_info',
#             'schema_attribute',
#             'parsing_column_name',
#         ]

#     def save(self, mapping_info, commit=True):
#         self.instance = MappingPair(**self.cleaned_data)
#         # self.instance.task = task
#         self.instance.mapping_info = mapping_info

#         if commit:
#             self.instance.save()
#             # self.instance.name = self.instance.file_original.name
#             # self.instance.save()
#         return self.instance

cssite/collect/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse
from django.views import generic, View
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.conf import settings

from .models import Account, Task, Participation, ParsedFile, SchemaAttribute, MappingInfo, MappingPair
from .forms import LoginForm, GradeForm, CreateTask

from string import ascii_lowercase
from random import choice, randint, random
from datetime import date, datetime, timedelta
import os
import pandas as pd
import mimetypes
import urllib


# 홈
def index(request):
    # if request.user.:
    #     return render(request, 'collect/index.html')
    if not request.user.is_authenticated:
        return render(request, 'collect/index.html')
    user = Account.objects.filter(user=request.user)[0]
    if user.role == "제출자":
        return redirect(reverse('collect:submitter'))
    elif user.role == "평가자":
        return redirect(reverse('collect:grader'))
    elif user.role == "관리자":
        return redirect(reverse('collect:manager'))


def fileList(request):
    """
    docstring
    """
    return render(request, 'manager/list.html', {
        'files': str(list(ParsedFile.objects.values())),
        'files_parsed': str(list(ParsedFile.objects.values())),
    })


# 회원가입
def signup(request):
    context = {}
    if request.method == "POST":
        if User.objects.filter(username=request.POST["username"]):
            context.update({'error': "이미 존재하는 ID입니다."})
            return render(request, 'collect/signup.html', context)
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"])
            account = Account(
                user=user,
                name=request.POST["name"],
                contact=request.POST["contact"],
                birth=request.POST["birth"],
                gender=request.POST["gender"],
                address=request.POST["address"],
                role=request.POST["role"])
            account.save()
            auth.login(request, user)
            if account.role == '제출자':
                return redirect(reverse('collect:submitter'))
            elif account.role == '평가자':
                return redirect(reverse('collect:grader'))
            elif account.role == '관리자':
                return redirect(reverse('manager:list'))
        else:
            context.update({'error': "비밀번호가 일치하지 않습니다."})
            return render(request, 'collect/signup.html', context)


# 로그인
def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            if user.account.role == '제출자':
                return redirect(reverse('collect:submitter'))
            elif user.account.role == '평가자':
                return redirect(reverse('collect:grader'))
            elif user.account.role == '관리자':
                return redirect(reverse('collect:manager'))
        messages.error(request, '로그인 실패. 다시 시도 해보세요.')
        return render(request, 'collect/login.html')
    else:
        return render(request, 'collect/login.html')


# 로그아웃
def logout(request):
    auth.logout(request)
    return redirect(reverse('collect:index'))


# 정보 조회
def userinfo(request, pk):
    user = request.user
    account = user.account
    context = {
        'user': user,
        'account': account
    }
    return render(request, 'collect/userinfo.html', context)


# 회원 정보 수정
def update(request, pk):
    if request.method == "POST":
        user = request.user
        if request.POST["password1"] == request.POST["password2"]:
            user.set_password(request.POST["password1"])
            user.save()
            account = user.account
            account.name = request.POST["name"]
            account.contact = request.POST["contact"]
            account.birth = request.POST["birth"]
            account.gender = request.POST["gender"]
            account.address = request.POST["address"]
            account.save()
            auth.login(request, user)
            if account.role == '제출자':
                return redirect(reverse('collect:tasks'))
            elif account.role == '평가자':
                return redirect(reverse('collect:allocated-parsedfiles'))
    return render(request, 'collect/update.html')


# 회원 탈퇴
def delete(request, pk):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect(reverse('collect:index'))


# 태스크 목록
class TaskList(View):
    def get(self, request):
        account = request.user.account
        task_list = Task.objects.all()
        participations = Participation.objects.filter(account=account)
        participate_tasks = [
            participation.task for participation in participations]
        context = {
            'task_list': task_list,
            'participate_tasks': participate_tasks
        }
        return render(request, 'collect/task.html', context)


# 태스크 상세 정보
class TaskDetail(View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        if request.user.account.role == '관리자':
            return render(request, 'manager/task_detail.html', {'task': task})
        return render(request, 'collect/task_detail.html', {'task': task})


# 태스크 참여
def create_participation(request, pk):
    user = request.user
    task = get_object_or_404(Task, pk=pk)
    participation = Participation(account=user.account, task=task)
    participation.save()
    return redirect(reverse('collect:participations'))


# 참여 중인 태스크 목록
class ParticipationList(View):
    def get(self, request):
        user = request.user
        participations = user.account.participations.all()
        return render(request, 'collect/participation.html', {'participations': participations})



# 제출자: 태스크 참여 취소
def delete_participation(request, pk):
    if request.user.account.role == '제출자':
        participation = get_object_or_404(Participation, pk=pk)
        participation.delete()
        return redirect(reverse('collect:participations'))


# 관리자: 태스크 참여 승인
def manager_acknowledge_participation(request, part_id):
    if request.user.account.role == '관리자':
        task = Participation.objects.filter(id=part_id)[0].task
        participation = get_object_or_404(Participation, pk=part_id)
        participation.admission = True
        participation.save()
        return redirect(reverse('show task', kwargs={'task_id': task.id}))


# 관리자: 태스크 참여 거절
def manager_delete_participation(request, part_id):
    if request.user.account.role == '관리자':
        task = Participation.objects.filter(id=part_id)[0].task
        participation = get_object_or_404(Participation, pk=part_id)
        participation.delete()
        return redirect(reverse('show task', kwargs={'task_id': task.id}))


# 관리자: 제출자가 제출한 파일 목록
def submittedfile_list(request, task_id, user_id):
    user = get_object_or_404(User, pk=user_id)
    task = get_object_or_404(Task, pk=task_id)
    parsedfile_list = user.account.parsed_submits.filter(task=task)
    total_tuple = sum(parsedfile.total_tuple if parsedfile.total_tuple else 0 for parsedfile in parsedfile_list)
    context = {
        'task': task,
        'parsedfile_list': parsedfile_list,
        'total_tuple': total_tuple
    }
    return render(request, 'manager/submitted_parsedfile.html', context)


def syncTotalTableFile(task):
    """
    파싱된 파일 전부 통합해 마스터 테이블에 등록
    사용처
     - 평가자가 패스한 후
     - 관리자가 태스크 조회할 때
    """
    attr = [ attrObj.attr for attrObj in SchemaAttribute.objects.filter(task=task) ]
    parsedfile_list = ParsedFile.objects.filter(task=task, pass_state=True)

    if not parsedfile_list:
        return None, "Pass된 튜플 없음"
    
    # df = pd.DataFrame(columns=attr)
    # df = pd.read_csv(os.path.join(settings.JOINED_PATH_DATA_PARSED, parsedfile_list[0].__str__()))
    file_list = []
    # print(df)
    # print("#####")

    for parsedFileObj in parsedfile_list:
        if not parsedFileObj.file_parsed is None:
            df_parsedFile = pd.read_csv(os.path.join(settings.JOINED_PATH_DATA_PARSED, parsedFileObj.__str__()), header=0, names=attr)
            # df.append(df_parsedFile, ignore_index=True)
            file_list.append(df_parsedFile)
            # print(df_parsedFile)
        # print(df)
        # print("#")

    if not os.path.exists(settings.JOINED_PATH_DATA_INTEGRATED):
        os.mkdir(settings.JOINED_PATH_DATA_INTEGRATED)
    
    download_file_path = os.path.join(settings.JOINED_PATH_DATA_INTEGRATED, task.name) + ".xlsx"
    df = pd.concat(file_list, axis=0, ignore_index=True)
    num_total_tuples = len(df)
    df.to_excel(download_file_path, header=attr, index=True)

    return download_file_path, num_total_tuples


# 제출자: 제출한 파일 목록 확인 및 업로드
def parsedFileListAndUpload(request, pk):
    os.makedirs(settings.JOINED_PATH_DATA_ORIGINAL, exist_ok=True)
    os.makedirs(settings.JOINED_PATH_DATA_PARSED, exist_ok=True)

    user = request.user
    task = get_object_or_404(Task, pk=pk)
    schemas = MappingInfo.objects.filter(task=task)

    if request.method == 'POST':
        submitter = Account.objects.filter(user=user)[0]
        # grader_pk = 2
        # grader = Account.objects.filter(id=grader_pk)[0]
        grader = None

        # random grader
        graders = Account.objects.filter(role="평가자")
        grading_end_date = None
        if graders:
            grader = choice(graders)
            grading_end_date = date.today() + timedelta(weeks=1)
        
        # check if the user is participating in the task
        participation = Participation.objects.filter(
            account=submitter, task=task)

cssite/collect/templates/collect/grader.html
{% load static %}
<head>
      
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">
  <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href = "{% static 'collect/cover.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/modal.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/parse.css' %}">
  <script src="{% static 'collect/login.js' %}" type="text/javascript"></script>
</head>

<body class = "text">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
      <div class="inner">
        <h3 class="masthead-brand">데이터베이스</h3>
        <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'collect:grader' %}">Home</a>
            <a class="nav-link active" href="{% url 'collect:graded-parsedfiles' %}">내 평가 기록</a>
            <a class="nav-link active" href="{% url 'collect:allocated-parsedfiles' %}">평가하기</a>

            {% comment %} 조회에 들어가서 수정할 수 있게 했습니다 H.K. {% endcomment %}
            {% comment %} <a class="nav-link active" href="{% url 'collect:update' user.id %}">정보 수정</a> {% endcomment %}
            <a class="nav-link active" href="{% url 'collect:userinfo' user.id %}">내 프로필</a>
            <a class="nav-link active" href="{% url 'collect:logout' %}">로그아웃</a>
        </nav>
      </div>
    </header>
    <main role="main" class="inner cover">
      {% block main_content %}
        <h1 class="cover-heading">평가자로 로그인되셨습니다.</h1>
      {% endblock main_content %}      
    </main>
    <footer class="mastfoot mt-auto">
      <div class="inner">
        <p>김지현 권순석 김하진 이동우 조성현</p>
      </div>
    </footer>
  </div>
  
</body> 

cssite/collect/templates/collect/manager.html
{% load static %}
<head>
      
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">
  <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href = "{% static 'collect/cover.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/modal.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/userlist.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/task_manager.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/participation.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/parse.css' %}">
 

  <script src="{% static 'collect/login.js' %}" type="text/javascript"></script>
  <script src="{% static 'collect/userlist.js' %}" type="text/javascript"></script>
</head>

<body class = "text">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
      <div class="inner">
        <h3 class="masthead-brand">데이터베이스</h3>
        <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'collect:manager' %}">Home</a>
            {% comment %}
            TODO:
            url에 문제가 있어서, 관리자는 자기 정보 수정할 수 없도록 했습니다.
            H.K.
            {% endcomment %}
            {% comment %} <a class="nav-link active" href="{% url 'collect:update' user.id %}">정보 수정</a> {% endcomment %}
            {% comment %} <a class="nav-link active" href="{% url 'collect:userinfo' user.id %}">내 정보 조회</a> {% endcomment %}
            <a class="nav-link active" href="{% url 'collect:users' %}">유저 정보 조회</a>
            <a class="nav-link active" href="{% url 'list tasks' %}">태스크 목록</a>
            <a class="nav-link active" href="{% url 'create task' %}">태스크 생성하기</a>

            <a class="nav-link active" href="{% url 'collect:logout' %}">로그아웃</a>
        </nav>
      </div>
    </header>

    <main role="main" class="inner cover">
      {% block main_content %}
        <h1 class="cover-heading">관리자로 로그인되셨습니다.</h1>
      {% endblock main_content %}
    </main>

    <footer class="mastfoot mt-auto">
      <div class="inner">
        <p>김지현 권순석 김하진 이동우 조성현</p>
      </div>
    </footer>
  </div>
    
</body> 

cssite/collect/templates/collect/task.html
{% extends 'collect/submitter.html' %}
{% block main_content %}
  <div id="taskListDiv"  style="overflow:auto;">
    <p class="taskListText">태스크 목록</p>

    <table class="taskListTable">
      <thead>
        <tr>
          <th>태스크 이름</th>
          <th>신청 상태</th>
        </tr>
      </thead>

      <tbody>
        {% for task in task_list %}
          {% if task.activation_state %}
            <tr>
              <td><a href="{% url 'collect:task-detail' task.id %}" style="color:rgb(48, 66, 146)" > {{ task.name }}</a></td>
              <td>
                {% if task not in participate_tasks %}
                  <a href="{% url 'collect:create-participation' task.id %}" style="color:rgb(48, 66, 146)" ><button>참여 신청</button></a>
                {% else %}
                  신청 완료
                {% endif %}
              </td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock main_content %}

cssite/collect/templates/collect/userlist.html
{% extends 'collect/manager.html' %}

                                      {% comment %} 

TODO:
관리자 페이지 헤더 통일하려고 상속으로 변경했습니다.
주석처리한 부분은 확인 후 지워주세요.
H.K.

                                      {% endcomment %}

{% comment %} {% load static %}
<head>
      
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">
  <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href = "{% static 'collect/cover.css' %}">
  <link rel="stylesheet" href = "{% static 'collect/userlist.css' %}">
  <script src="{% static 'collect/login.js' %}" type="text/javascript"></script>
  <script src="{% static 'collect/userlist.js' %}" type="text/javascript"></script>

</head>

<body class = "text">
  
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
      <div class="inner">
        <h3 class="masthead-brand">데이터베이스</h3>
        <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'collect:manager' %}">Home</a>
            <a class="nav-link active" href="{% url 'collect:logout' %}">로그아웃</a>
            <a class="nav-link active" href="{% url 'collect:update' user.id %}">정보 수정</a>
            <a class="nav-link active" href="{% url 'collect:userinfo' user.id %}">내 정보 조회</a>
            <a class="nav-link active" href="{% url 'collect:delete' user.id %}">회원 탈퇴</a>
        </nav>
        
      </div>
    </header>
    <main role="main" class="inner cover"> {% endcomment %}
      {% block main_content %}
      <div class="containerDiv">
       <p class="titleText">유저 정보 조회</p>
        <div id="searchDiv">
          <p class="searchDivTitle">유저 검색하기</p>
         
          <form action="{% url 'collect:users' %}" method="get">

            <p class="userInfoText" style="top:85px;">아이디</p>
            <input class="userInfoInput" type="text" name="username" style="top:85px;">

            <p class="userInfoText" style="top:125px;">성별</p>
            <select class="userInfoInput"  name="gender" style="top:125px;">
              <option value="">--</option>
              <option value="남성">남성</option>
              <option value="여성">여성</option>
            </select>

            <p class="userInfoText" style="top:165px;">역할</p>
            <select class="userInfoInput" name="role" style="top:165px;">
              <option value="">--</option>
              <option value="제출자">제출자</option>
              <option value="평가자">평가자</option>
            </select>
              
            <p class="userInfoText" style="top:225px;">생년월일</p>
            <input class="userInfoInput" type="date" name="birth1" style="top:205px;">
            <p class="userInfoText" style="top:230px; left:40%; font-size:30px">~</p>
            <input class="userInfoInput" type="date" name="birth2" style="top:240px;right:15%;">

            <p class="userInfoText" style="top:280px;">참여 태스크</p>
            <select class="userInfoInput" name="taskname" style="top:280px;">
              <option value="">--</option>
              {% for task in tasks %}
              <option value="{{ task.name }}">{{ task.name }}</option>
              {% endfor %}
            </select>
            <div class="initButton" style="top:330px;" onclick="clearSearchInput(0);">초기화</div>
            <input class="searchButton" type="submit" value="검색" style="top:330px">
          </form>
        </div>
        <div id="searchFoldButton" onclick="foldSearchDiv()"> ◀ </div>

       <div id="userInfoDiv" style="overflow:auto;">
        <table class="userInfoTable">
          <thead>
            <tr>
              <th>역할</th>
              <th>ID</th>
              <th>생년월일</th>
              <th>성별</th>
              <th>참여중인 태스크</th>
              <th>상세조회</th>
            </tr>
          </thead>
          <tbody>
            {% for account in accounts %}
              {% if account.role != "관리자" %}
                <tr>
                  <td>{{ account.role }}</td>
                  <td> {{ account.user.username }}</td>
                  <td>{{ account.birth }}</td>
                  <td>{{ account.gender }}</td>
                  <td>
                    {% for participation in account.participations.all %}
                      {% if participation.admission %}
                        {{ participation.task.name }} 
                      {% endif %}
                    {% endfor %}</td>
                  <td> <a href="{% url 'collect:user-detail' account.user.id %}" style="color:rgb(48, 66, 146)">상세조회</a> </td>
                </tr>
              {% endif %}
            {% endfor %}
          </tbody>

        </table>
       </div>
      
      </div>
      <!-- end of containerDiv -->

      

    
    {% endblock main_content %}
            
    {% comment %} 
    

    </main>

  

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>김지현 권순석 김하진 이동우 조성현</p>
        </div>
      </footer>
    </div>
    
  </body>  {% endcomment %}